[2024-02-25T15:38:40.648+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2024-02-25T15:38:37.381780+00:00 [queued]>
[2024-02-25T15:38:40.655+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2024-02-25T15:38:37.381780+00:00 [queued]>
[2024-02-25T15:38:40.655+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-25T15:38:40.664+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2024-02-25 15:38:37.381780+00:00
[2024-02-25T15:38:40.672+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'spark_airflow_dag', 'spark_submit_task', 'manual__2024-02-25T15:38:37.381780+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/spark_etl_dag.py', '--cfg-path', '/tmp/tmp2quzy474']
[2024-02-25T15:38:40.677+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask spark_submit_task
[2024-02-25T15:38:40.668+0000] {standard_task_runner.py:57} INFO - Started process 646 to run task
[2024-02-25T15:38:40.715+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-25T15:38:40.786+0000] {task_command.py:410} INFO - Running <TaskInstance: spark_airflow_dag.spark_submit_task manual__2024-02-25T15:38:37.381780+00:00 [running]> on host 1db92e94aa46
[2024-02-25T15:38:40.852+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_airflow_dag' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-25T15:38:37.381780+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-25T15:38:37.381780+00:00'
[2024-02-25T15:38:40.860+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-02-25T15:38:40.865+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master spark://2bd2270b4c4b:7077 --conf spark.master=spark://spark-master:7077 --name arrow-spark /opt/airflow/dags/spark_etl.py
[2024-02-25T15:38:41.129+0000] {spark_submit.py:490} INFO - /home/airflow/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-02-25T15:54:58.888+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-02-25T15:54:59.090+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 646. PIDs of all processes in the group: [647, 646]
[2024-02-25T15:54:59.095+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 646
[2024-02-25T15:54:59.138+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-25T15:54:59.364+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=647, status='terminated', started='15:38:40') (647) terminated with exit code None
[2024-02-25T15:54:59.978+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 409, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 458, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-02-25T15:55:00.127+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=spark_airflow_dag, task_id=spark_submit_task, execution_date=20240225T153837, start_date=20240225T153840, end_date=20240225T155500
[2024-02-25T15:55:00.243+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 4 for task spark_submit_task (Task received SIGTERM signal; 646)
[2024-02-25T15:55:00.990+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=646, status='terminated', exitcode=1, started='15:38:40') (646) terminated with exit code 1
